"""add scoring tables

Revision ID: 8dcd53ce4df0
Revises: 892c91aaffe3
Create Date: 2026-02-27 11:12:41.585630

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8dcd53ce4df0"
down_revision: str | Sequence[str] | None = "892c91aaffe3"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "scoring_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("profile_id", sa.Integer(), nullable=False),
        sa.Column("ingestion_run_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum("started", "finished", "failed", name="scoringrunstatus"),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("meta", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["ingestion_run_id"], ["ingestion_runs.id"]),
        sa.ForeignKeyConstraint(["profile_id"], ["candidate_profiles.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scoring_runs_finished_at"), "scoring_runs", ["finished_at"], unique=False
    )
    op.create_index(
        op.f("ix_scoring_runs_ingestion_run_id"), "scoring_runs", ["ingestion_run_id"], unique=False
    )
    op.create_index(
        op.f("ix_scoring_runs_profile_id"), "scoring_runs", ["profile_id"], unique=False
    )
    op.create_index(
        op.f("ix_scoring_runs_started_at"), "scoring_runs", ["started_at"], unique=False
    )
    op.create_index(op.f("ix_scoring_runs_status"), "scoring_runs", ["status"], unique=False)

    op.create_table(
        "score_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("scoring_run_id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column(
            "status",
            sa.Enum("started", "finished", "failed", name="scoreitemstatus"),
            nullable=False,
        ),
        sa.Column("score", sa.Float(), nullable=True),
        sa.Column("skills_matched", sa.JSON(), nullable=False),
        sa.Column("skills_missing", sa.JSON(), nullable=False),
        sa.Column("reasons", sa.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.ForeignKeyConstraint(["job_id"], ["job_postings.id"]),
        sa.ForeignKeyConstraint(["scoring_run_id"], ["scoring_runs.id"]),
    )
    op.create_index(op.f("ix_score_items_job_id"), "score_items", ["job_id"], unique=False)
    op.create_index(
        op.f("ix_score_items_scoring_run_id"), "score_items", ["scoring_run_id"], unique=False
    )
    op.create_index(op.f("ix_score_items_status"), "score_items", ["status"], unique=False)

    op.create_table(
        "scoring_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("traceback", sa.String(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=False),
        sa.ForeignKeyConstraint(["item_id"], ["score_items.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_scoring_errors_error_type"), "scoring_errors", ["error_type"], unique=False
    )
    op.create_index(op.f("ix_scoring_errors_item_id"), "scoring_errors", ["item_id"], unique=False)

    with op.batch_alter_table("score_items") as batch_op:
        batch_op.add_column(sa.Column("error_id", sa.Integer(), nullable=True))
        batch_op.create_index(op.f("ix_score_items_error_id"), ["error_id"], unique=False)
        batch_op.create_foreign_key(
            "fk_score_items_error_id_scoring_errors",
            "scoring_errors",
            ["error_id"],
            ["id"],
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("score_items") as batch_op:
        batch_op.drop_constraint("fk_score_items_error_id_scoring_errors", type_="foreignkey")
        batch_op.drop_index(op.f("ix_score_items_error_id"))
        batch_op.drop_column("error_id")

    op.drop_index(op.f("ix_scoring_errors_item_id"), table_name="scoring_errors")
    op.drop_index(op.f("ix_scoring_errors_error_type"), table_name="scoring_errors")
    op.drop_table("scoring_errors")

    op.drop_index(op.f("ix_score_items_status"), table_name="score_items")
    op.drop_index(op.f("ix_score_items_scoring_run_id"), table_name="score_items")
    op.drop_index(op.f("ix_score_items_job_id"), table_name="score_items")
    op.drop_table("score_items")

    op.drop_index(op.f("ix_scoring_runs_status"), table_name="scoring_runs")
    op.drop_index(op.f("ix_scoring_runs_started_at"), table_name="scoring_runs")
    op.drop_index(op.f("ix_scoring_runs_profile_id"), table_name="scoring_runs")
    op.drop_index(op.f("ix_scoring_runs_ingestion_run_id"), table_name="scoring_runs")
    op.drop_index(op.f("ix_scoring_runs_finished_at"), table_name="scoring_runs")
    op.drop_table("scoring_runs")
    # ### end Alembic commands ###
