"""init schema

Revision ID: ed045dda9c96
Revises:
Create Date: 2026-02-27 10:12:44.213689

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed045dda9c96"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ingestion_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status", sa.Enum("started", "finished", "failed", name="runstatus"), nullable=False
        ),
        sa.Column("meta", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingestion_runs_source"), "ingestion_runs", ["source"], unique=False)
    op.create_table(
        "job_postings",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("source", sa.String(length=64), nullable=False),
        sa.Column("source_item_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=512), nullable=True),
        sa.Column("company", sa.String(length=256), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("raw", sqlite.JSON(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_job_postings_source"), "job_postings", ["source"], unique=False)
    op.create_index(
        op.f("ix_job_postings_source_item_id"), "job_postings", ["source_item_id"], unique=False
    )
    op.create_table(
        "ingestion_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("run_id", sa.Integer(), nullable=False),
        sa.Column("source_item_id", sa.String(length=128), nullable=False),
        sa.Column("status", sa.Enum("ok", "error", "skipped", name="itemstatus"), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=True),
        sa.Column("raw", sqlite.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["job_postings.id"],
        ),
        sa.ForeignKeyConstraint(
            ["run_id"],
            ["ingestion_runs.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ingestion_items_job_id"), "ingestion_items", ["job_id"], unique=False)
    op.create_index(op.f("ix_ingestion_items_run_id"), "ingestion_items", ["run_id"], unique=False)
    op.create_index(
        op.f("ix_ingestion_items_source_item_id"),
        "ingestion_items",
        ["source_item_id"],
        unique=False,
    )
    op.create_table(
        "ingestion_errors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("item_id", sa.Integer(), nullable=False),
        sa.Column("error_type", sa.String(length=128), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("traceback", sa.Text(), nullable=True),
        sa.Column("data", sqlite.JSON(), nullable=False),
        sa.ForeignKeyConstraint(
            ["item_id"],
            ["ingestion_items.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ingestion_errors_item_id"), "ingestion_errors", ["item_id"], unique=True
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ingestion_errors_item_id"), table_name="ingestion_errors")
    op.drop_table("ingestion_errors")
    op.drop_index(op.f("ix_ingestion_items_source_item_id"), table_name="ingestion_items")
    op.drop_index(op.f("ix_ingestion_items_run_id"), table_name="ingestion_items")
    op.drop_index(op.f("ix_ingestion_items_job_id"), table_name="ingestion_items")
    op.drop_table("ingestion_items")
    op.drop_index(op.f("ix_job_postings_source_item_id"), table_name="job_postings")
    op.drop_index(op.f("ix_job_postings_source"), table_name="job_postings")
    op.drop_table("job_postings")
    op.drop_index(op.f("ix_ingestion_runs_source"), table_name="ingestion_runs")
    op.drop_table("ingestion_runs")
    # ### end Alembic commands ###
